package models

const (
	CONST_DS_ENTITY_NETWORK = "NETWORK"
	CONST_DS_ENTITY_NETWORKCONFIG = "NETWORKCONFIG"
	CONST_DS_ENTITY_CHAINCONFIG = "CHAINCONFIG"
	CONST_DS_ENTITY_NETWORKMESSAGE = "NETWORKMESSAGE"
	CONST_DS_ENTITY_NODE = "NODE"
	CONST_DS_ENTITY_ADDRESSNODE = "ADDRESSNODE"

	CONST_DS_ENTITY_CUSTOMER = "CUSTOMER"
	CONST_DS_ENTITY_NAMESPACE = "NAMESPACE"
	CONST_DS_ENTITY_APITOKEN = "APITOKEN"
	//
	CONST_DS_ENTITY_WALLET = "WALLET"
	CONST_DS_ENTITY_CURRENCY = "CURRENCY"
	CONST_DS_ENTITY_ASSET = "ASSET"
	CONST_DS_ENTITY_EXCHANGE = "EXCHANGE"
	//
	CONST_DS_ENTITY_ACCOUNT_USER = "USER"
	CONST_DS_ENTITY_ADDRESS = "ADDRESS"
	CONST_DS_ENTITY_BALANCE = "BALANCE"
	CONST_DS_ENTITY_PERMISSION = "PERMISSION"
	//
	CONST_DS_ENTITY_STREAM = "STREAM"
	//
	CONST_DS_ENTITY_BILLING_RECORD = "BILLING_RECORD"
	CONST_DS_ENTITY_TX = "TX"
	CONST_DS_ENTITY_TRANSACTION = "TRANSACTION"
)
